config/routes.rb
Rails.application.routes.draw do
  resources :due_types
  resources :dues
  resources :agreements
  resources :tenants
  devise_for :users
  resources :properties
  # get 'home/index'
  root 'dues#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :user
    has_one :agreement
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
    end
  

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    # @property = Property.new
    @property = current_user.properties.build
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    # @property = Property.new(property_params)
    @property = current_user.properties.build(property_params)
    respond_to do |format|
      if @property.save
        format.html { redirect_to properties_path, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    if @property.rented
      redirect_to properties_path, alert: 'Property is rented, you cannot delete it.'
    else  
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully deleted.' }
      format.json { head :no_content }
    end  
    end
  end

  def correct_user 
    @property = current_user.properties.find_by(id: params[:id])
    redirect_to properties_path, alert: 'Not Authorized to edit this property' if @property.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:address, :postcode, :city, :rented, :user_id)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :address %>
    <%= form.text_field :address, :required => 'required', class:"form-control" %>
    <br/>
  </div>

  <div class="field form-group"">
    <%= form.label :postcode %>
    <%= form.text_field :postcode, :required => 'required', class:"form-control" %>
    <br/>
  </div>

  <div class="field form-group>
    <%= form.label :city %>
    <%= form.text_field :city, :required => 'required', class:"form-control" %>
  </div>

  <!-- <div class="field form-group"">
    <%= form.label :rented %>
    <%= form.check_box :rented, class:"form-control" %>
  </div> -->

  <div class="actions">
    <%= form.submit class:"btn btn-success btn-bottom-margin btn-top-margin" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="my-jumbotron shadow-sm">
<h1>Editing Property</h1>
<%= render 'form', property: @property %>
<%= link_to 'Cancel', properties_path, class:'btn btn-secondary' %>
</div>

app/views/properties/index.html.erb
<!-- <p id="notice" class="alert alert-warning alert-dismissible"><%= notice %></p> -->

<div class="title-and-add-button">
<h1>Properties</h1>
<%= link_to '+', new_property_path, class:"btn btn-success" %>

</div>

<table class="table table-bordered table-hover shadow-sm">
  <thead class="thead-dark">
    <tr>
      <th>Address</th>
      <th>Postcode</th>
      <th>City</th>
      <th>Rented</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <% if property.user_id == current_user.id %>
      <tr>
        <td><%= property.address %></td>
        <td><%= property.postcode %></td>
        <td><%= property.city %></td>
        <td><% if property.rented %>Yes<% else %>No<% end %></td>
        <td>
          <%= link_to edit_property_path(property), class:"btn btn-outline-secondary" do %>
            <i class='far fa-edit'> </i>
          <% end %>
         </td>
         <td>
            <%= link_to property, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" do %>
              <i class='fas fa-trash'> </i>
            <% end %> 
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/properties/new.html.erb
<div class="my-jumbotron shadow-sm">
<h1>Add New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Cancel', properties_path, class:"btn btn-secondary" %>
</div>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>
<div class="my-jumbotron">
<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @property.postcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @property.city %>
</p>

<p>
  <strong>Rented:</strong>
  <%= @property.rented %>
</p>

<%= link_to 'Edit', edit_property_path(@property), class:"btn btn-secondary" %>
<%= link_to 'Back', properties_path, class:"btn btn-secondary btn-dark" %>
</div>