config/routes.rb
Rails.application.routes.draw do
  resources :due_types
  resources :dues
  resources :agreements
  resources :tenants
  devise_for :users
  resources :properties
  # get 'home/index'
  root 'dues#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-custom shadow-sm">
  <div class="container-fluid">
   <!-- <%= link_to "Rental", root_path, class:"navbar-brand" %> -->
  <%= link_to root_path do %>
    <%= image_tag "rental-logo.png", class:"navbar-brand", style: "max-height:4rem;" %>
 <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
   
<% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Properites", properties_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Tenants", tenants_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Agreements", agreements_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Dues", dues_path, class:"nav-link" %>
          </li>
        <li class="nav-item">
        <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

<% else %>        

        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>




        <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
        </li>

<% end %>        
      
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li -->
      </ul>
      <!-- <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>

app/views/home/index.html.erb
This is the index page