config/routes.rb
Rails.application.routes.draw do
  resources :due_types
  resources :dues
  resources :agreements
  resources :tenants
  devise_for :users
  resources :properties
  # get 'home/index'
  root 'dues#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/due_types_controller.rb
class DueTypesController < ApplicationController
  before_action :set_due_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /due_types
  # GET /due_types.json
  def index
    @due_types = DueType.all
  end

  # GET /due_types/1
  # GET /due_types/1.json
  def show
  end

  # GET /due_types/new
  def new
    @due_type = current_user.due_types.build
  end

  # GET /due_types/1/edit
  def edit
  end

  # POST /due_types
  # POST /due_types.json
  def create
    # @due_type = DueType.new(due_type_params)
    @due_types = current_user.due_types
    @due_type = current_user.due_types.build(due_type_params)
    respond_to do |format|
      if @due_types.find_by(name: @due_type.name) 
        format.html { redirect_to due_types_path, alert: 'This due type already exists.' }
        format.json { render json: @due_type.errors, status: :unprocessable_entity }
      elsif  @due_type.save
        format.html { redirect_to due_types_path, notice: 'Due type was successfully created.' }
        format.json { render :show, status: :created, location: @due_type }
      else
        format.html { render :new }
        format.json { render json: @due_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /due_types/1
  # PATCH/PUT /due_types/1.json
  def update
    respond_to do |format|
      if @due_type.update(due_type_params)
        format.html { redirect_to due_types_path, notice: 'Due type was successfully updated.' }
        format.json { render :show, status: :ok, location: @due_type }
      else
        format.html { render :edit }
        format.json { render json: @due_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /due_types/1
  # DELETE /due_types/1.json
  def destroy
    if  current_user.dues.find_by(due_type_id: @due_type.id)
      redirect_to due_types_path, alert: 'You cannot delete. This type is in use.'
    else  
    @due_type.destroy
    respond_to do |format|
      format.html { redirect_to due_types_url, notice: 'Due type was successfully deleted.' }
      format.json { head :no_content }
    end  
    end
  end

  def correct_user 
    @due_type = current_user.due_types.find_by(id: params[:id])
    redirect_to due_types_path, alert: 'Not Authorized to edit this type' if @due_type.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_due_type
      @due_type = DueType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def due_type_params
      params.require(:due_type).permit(:name, :user_id)
    end
end

app/helpers/due_types_helper.rb
module DueTypesHelper
end

app/views/due_types/_form.html.erb
<%= form_with(model: due_type, local: true) do |form| %>
  <% if due_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(due_type.errors.count, "error") %> prohibited this due_type from being saved:</h2>

      <ul>
        <% due_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group col-3">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="actions form-group">
    <%= form.submit class:"btn btn-success btn-bottom-margin btn-top-margin" %>
  </div>
<% end %>

app/views/due_types/edit.html.erb
<div class="my-jumbotron shadow-sm">
<h1>Editing Due Type</h1>
<%= render 'form', due_type: @due_type %>
<%= link_to 'Cancel', due_types_path, class: "btn btn-secondary" %>
</div>

app/views/due_types/index.html.erb
<div class="title-and-add-button">
<h1>Due and bill Types</h1>
<%= link_to '+', new_due_type_path, class:"btn btn-success " %>
</div>
<table class="table table-bordered table-hover shadow-sm">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @due_types.each do |due_type| %>
      <% if due_type.user_id == current_user.id %>
      <tr>
        <td><%= due_type.name %></td>
        <td>
        <%= link_to edit_due_type_path(due_type), class:"btn btn-outline-secondary" do %>
          <i class='far fa-edit'> </i>
        <% end %>
        </td>
        <td>
        <%= link_to due_type, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" do %>
          <i class='fas fa-trash'> </i>
          <% end %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to dues', dues_path, class:"btn btn-secondary" %>

app/views/due_types/new.html.erb
<div class="my-jumbotron shadow-sm">
<h1>New Due Type</h1>
<%= render 'form', due_type: @due_type %>
<%= link_to 'Cancel', due_types_path, class:"btn btn-secondary" %>
</div>

app/views/due_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @due_type.name %>
</p>

<%= link_to 'Edit', edit_due_type_path(@due_type) %> |
<%= link_to 'Back', due_types_path %>