config/routes.rb
Rails.application.routes.draw do
  resources :due_types
  resources :dues
  resources :agreements
  resources :tenants
  devise_for :users
  resources :properties
  # get 'home/index'
  root 'dues#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/due.rb
class Due < ApplicationRecord
    belongs_to :due_type
    belongs_to :user

    enum status: [:Recent, :Close, :Delayed, :Paid]
end

app/models/due_type.rb
class DueType < ApplicationRecord
    belongs_to :user
    has_many :due
end

app/controllers/dues_controller.rb
class DuesController < ApplicationController
  before_action :set_due, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /dues
  # GET /dues.json
  def index
    @dues = current_user.dues
    @tenant_dues = current_user.dues.select { |due| due.tenant_id != nil }
    @bills = current_user.dues.select { |bill| bill.property_id != nil }
    @due_types = current_user.due_types
    @tenants = current_user.tenants
    @properties = current_user.properties
    @dues.each do |due|

    days_left = due.payment_date - Date.today
    left_to_pay = due.amount - due.paid_amount

    if left_to_pay >0
      if days_left < 0
    due.status = 2
      end
      if (days_left < 4) && (days_left >=0)
        due.status = 1
      end
    end
    #   if  left_to_pay <= 0
    #    due.status = 3
    #  end
    
    due.save
    end
  end

  # GET /dues/1
  # GET /dues/1.json
  def show
  end

  # GET /dues/new
  def new
    @due = current_user.dues.build
    @due_types = current_user.due_types
    @properties = current_user.properties
    @tenants = current_user.tenants
  end

  # GET /dues/1/edit
  def edit
    @properties = current_user.properties
    @tenants = current_user.tenants
    @due_types = current_user.due_types
    @to_pay = @due.amount - @due.paid_amount
    @today = Date.today
  end

  # POST /dues
  # POST /dues.json
  def create
    @properties = current_user.properties
    @tenants = current_user.tenants
    @agreements = current_user.agreements
    @due = current_user.dues.build(due_params)
    @tenant_due = current_user.dues.build(due_params)

    if @due.property_id && @agreements.find_by(property_id: @tenant_due.property_id)
      id_to_assign = @agreements.find_by(property_id: @tenant_due.property_id).tenant_id
      @tenant_due.tenant_id = id_to_assign
      @tenant_due.property_id = nil 
      respond_to do |format|
        if @due.save && @tenant_due.save
            format.html { redirect_to dues_path, notice: 'Bill to pay and due to collect were successfully created.' }
            format.json { render :show, status: :created, location: @due }
        else
            format.html { render :new }
            format.json { render json: @due.errors, status: :unprocessable_entity }
        end
      end
    else  
      respond_to do |format|
        if  @due.save    
            format.html { redirect_to dues_path, notice: 'Bill to pay was successfully created.' }
            format.json { render :show, status: :created, location: @due }  
        else
            format.html { render :new }
            format.json { render json: @due.errors, status: :unprocessable_entity }
        end
      end

    end
  end

  # PATCH/PUT /dues/1
  # PATCH/PUT /dues/1.json
  def update
    to_add = @due.paid_amount
    respond_to do |format|
      if @due.update(due_params)
        format.html { redirect_to dues_path, notice: 'Due was successfully updated.' }
        format.json { render :show, status: :ok, location: @due }
      else
        format.html { render :edit }
        format.json { render json: @due.errors, status: :unprocessable_entity }
      end
      @due.paid_amount +=to_add
      left_to_pay = @due.amount - @due.paid_amount
     if  left_to_pay <= 0
      @due.status = 3
    end
    @due.save
    end
  end

  # DELETE /dues/1
  # DELETE /dues/1.json
  def destroy
    @due.destroy
    respond_to do |format|
      format.html { redirect_to dues_url, notice: 'Due was successfully canceled.' }
      format.json { head :no_content }
    end
  end

  def correct_user 
    @due = current_user.dues.find_by(id: params[:id])
    redirect_to dues_path, alert: 'Not Authorized to edit this type' if @due.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_due
      @due = Due.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def due_params
      params.require(:due).permit(:due_type_id, :agreement_id, :property_id, :tenant_id, :period_from, :period_to, :amount, :paid_amount, :paid_on, :payment_date, :user_id, :status)
    end
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/views/dues/_form.html.erb
<%= form_with(model: due, local: true) do |form| %>
  <% if due.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(due.errors.count, "error") %> prohibited this due from being saved:</h2>

      <ul>
        <% due.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <!-- Paying a bill -->
  <% if params[:operation]== 'pay' %> 
 <div>
    You've paid <%= @due.paid_amount %> 
    <br>
    <%= @to_pay %> out of <%= @due.amount %> left to pay.
    <br>
    How much do you want to pay?
  <div class="field form-group col-1 ">
    <%= form.number_field :paid_amount, value: number_to_currency(@to_pay, delimiter: '', unit: ''), class:"form-control" %>
  </div>
</div>
<div class="field form-group col-3">
  <%= form.label :paid_on %>
  <%= form.date_field :paid_on, value: @today, class: "form-control"%>
</div> 

<!-- Collecting a due -->
<% elsif params[:operation]== 'collect' %> 
<div class="field form-group col-3"">
  You've collected <%= @due.paid_amount %> 
  <br>
  <%= @to_pay %> out of <%= @due.amount %> left to collect.
  <br>
    <%= form.label 'how much do you want to collect'%>
  <%= form.number_field :paid_amount, value: number_to_currency(@to_pay, delimiter: '', unit: '') %>
</div>
<div class="field form-group col-3">
  <%= form.label :paid_on %>
  <%= form.date_field :paid_on, value: @today, class: "form-control" %>
</div> 

 <% else %>
<div class="row">
 <!-- Creating a new due -->
 <div class="field form-group col-3">
  <%= form.label :due_type_id %>
  <%= form.select( :due_type_id, @due_types.collect { |type| [type.name, type.id] }, {}, {class: "form-select"}) %>
</div>
<% end %>

 <!-- Only for bills to pay -->
<% if params[:payer]== 'property' %>
<div class="field form-group col-3">
  <%= form.label :property_id %>
  <%= form.select( :property_id, @properties.collect { |property| [property.address, property.id] }, {}, {class: "form-select"}) %>
</div>
</div>
<% end %> 

 <!-- Only for dues to collect -->
<% if params[:payer]== 'tenant' %>
<div class="field form-group col-3">
  <%= form.label :tenant_id %>
  <%= form.select( :tenant_id, @tenants.collect { |tenant| [tenant.name, tenant.id] }, {}, {class: "form-select"}) %>
</div>
</div>
<% end %> 


<% if params[:payer] %>
<div class="row">
  <div class="field form-group col-3">
    <%= form.label :period_from %>
    <%= form.date_field :period_from, :required => 'required', class: "form-control"%>
  </div>
  <div class="field form-group col-3">
    <%= form.label :period_to %>
    <%= form.date_field :period_to, :required => 'required', class: "form-control"%>
  </div>
</div>
<div class="row">
  <div class="field form-group col-1">
    <%= form.label :amount %>
    <%= form.text_field :amount, :required => 'required', class:"form-control" %>
  </div>
  <div class="field form-group col-3">
    <%= form.label :payment_date %>
    <%= form.date_field :payment_date, :required => 'required', class:"form-control" %>
  </div>
</div>
<% end %>

<div class="field form-group"">
<%= form.number_field :user_id, id: :due_user_id, value: current_user.id, class:"form-control", type: :hidden %>
</div>

<% if params[:payer]== 'property' %>
<div class="actions">
  <%= form.submit "Create a bill to pay", class:"btn btn-success btn-bottom-margin btn-top-margin" %>
</div>
<% elsif params[:payer]== 'tenant' %>
<%= form.submit "Create a due to collect", class:"btn btn-success btn-bottom-margin btn-top-margin" %>
<% elsif params[:operation]== 'pay' %>
<%= form.submit "Pay the bill", class:"btn btn-success btn-bottom-margin btn-top-margin" %>
<% elsif params[:operation]== 'collect' %>
<%= form.submit "Collect the due", class:"btn btn-success btn-bottom-margin btn-top-margin" %>
<% else %>
  <div class="actions">
    <%= form.submit class:"btn btn-success btn-bottom-margin btn-top-margin" %>
  </div>
<% end %>

<% end %>

app/views/dues/edit.html.erb
<div class="my-jumbotron shadow-sm">

<h1><%= params[:operation].humanize %>  the <%= @due_types.find_by_id(@due.due_type_id).name %> - <%= @due.amount %>$</h1>
<% if params[:operation]== 'pay' %> 
Property: <%= @properties.find_by_id(@due.property_id).address %>
<% elsif params[:operation]== 'collect' %> 
Tenant: <%= @tenants.find_by_id(@due.tenant_id).name %>
<% end %>
<!-- Bill data here -->


<%= render 'form', due: @due %>
<%= link_to 'Back', dues_path, class:'btn btn-secondary' %>
</div>

app/views/dues/index.html.erb
<div class="title-and-add-button">
  <div class="left d-flex">
    <div class="table-title">Bills to pay</div>
    <div class="mt-auto mb-auto"><%= link_to '+', new_due_path(:payer => 'property'), class:"btn btn-success " %> </div>
  </div>
    <div class="right">
    <%= link_to 'Edit due types', due_types_path, class:"btn-sm btn-success " %>
  </div>
</div>


<table class="table table-bordered table-hover shadow-sm">
  <thead>
    <tr>
      <!-- <th>Agreement</th> -->
      <th>Property</th>
      <th>Type</th>
      <!-- <th>Tenant</th> -->
      <th>Period from</th>
      <th>Period to</th>
      <th>Amount</th>
      <th>Paid amount</th>
      <th>Paid on</th>
      <th>Payment date</th>
      <th>Status</th>
      <th>Pay</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <% if bill.user_id == current_user.id %>
      <tr class="<%= bill.status.downcase %>">
        <!-- <td><%= bill.agreement_id %></td> -->
        <td><%= @properties.find_by_id(bill.property_id).address %></td>
        <td><%= @due_types.find_by_id(bill.due_type_id).name %></td>
        <!-- <td><%= bill.tenant_id %></td> -->
        <td><%= bill.period_from %></td>
        <td><%= bill.period_to %></td>
        <td><%= bill.amount %></td>
        <td><%= bill.paid_amount %></td>
        <td><%= bill.paid_on %></td>
        <td><%= bill.payment_date %></td>
        <td><%= bill.status %></td>
        <td><%= link_to 'Pay', edit_due_path(bill, :operation => 'pay'), class:"btn btn-outline-success" %></td>
        <td>
        <%= link_to bill, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" do %>
          <i class='fas fa-trash'> </i>
        <% end %> 
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'Bill types', due_types_path, class:"btn btn-secondary" %> -->
<div class="title-and-add-button">
  <div class="left d-flex">
    <div class="table-title">Dues to collect</div>
    <div class="mt-auto mb-auto"><%= link_to '+', new_due_path(:payer => 'tenant'), class:"btn btn-success " %> </div>
  </div>
    <div class="right">
    <%= link_to 'Edit due types', due_types_path, class:"btn-sm btn-success " %>
  </div>
</div>


<table class="table table-bordered table-hover shadow-sm">
  <thead>
    <tr>
      <th>Tenant</th>
      <th>Type</th>
      <th>Period from</th>
      <th>Period to</th>
      <th>Amount</th>
      <th>Paid amount</th>
      <th>Paid on</th>
      <th>Payment date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tenant_dues.each do |due| %>
      <% if due.user_id == current_user.id %>
      <tr class="<%= due.status.downcase %>">
        <!-- <td><%= due.agreement_id %></td> -->
        <!-- <td><%= due.property_id %></td> -->
        <td><%= @tenants.find_by_id(due.tenant_id).name %></td>
        <td><%= @due_types.find_by_id(due.due_type_id).name %></td>
        <td><%= due.period_from %></td>
        <td><%= due.period_to %></td>
        <td><%= due.amount %></td>
        <td><%= due.paid_amount %></td>
        <td><%= due.paid_on %></td>
        <td><%= due.payment_date %></td>
        <td><%= due.status %></td>
        <td><%= link_to 'Collect', edit_due_path(due, :operation => 'collect'), class:"btn btn-outline-success" %></td>
        <td>
          <%= link_to due, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" do %>
          <i class='fas fa-trash'> </i>
        <% end %>  
          </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>



<!-- TEST TESET TEST -->
<!-- <h1>All the dues objects- for testing</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Type</th>
      <th>Rent</th>
      <th>Property</th>
      <th>Tenant</th>
      <th>Period from</th>
      <th>Period to</th>
      <th>Amount</th>
      <th>Paid amount</th>
      <th>Paid on</th>
      <th>Payment date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dues.each do |due| %>
      <% if due.user_id == current_user.id %>
      <tr>
        <td><%= @due_types.find_by_id(due.due_type_id).name %></td>
        <td><%= due.agreement_id %></td>
        <td><%= due.property_id %></td>
        <td><%= due.tenant_id %></td>
        <td><%= due.period_from %></td>
        <td><%= due.period_to %></td>
        <td><%= due.amount %></td>
        <td><%= due.paid_amount %></td>
        <td><%= due.paid_on %></td>
        <td><%= due.payment_date %></td>
        <td><%= due.user_id %></td>
        <td><%= link_to 'Pay', edit_due_path(due, :operation => 'pay') %></td>
        <td><%= link_to 'Cancel', due, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table> -->

app/views/dues/new.html.erb
<div class="my-jumbotron shadow-sm">
<h1>New
<% if params[:payer]== 'property' %>bill to pay <% end %>
<% if params[:payer]== 'tenant' %>due to collect  <% end %>
</h1>
<%= render 'form', due: @due %>
<%= link_to 'Cancel', dues_path, class:"btn btn-secondary" %>
</div>

app/views/dues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @due.due_type_id %>
</p>

<p>
  <strong>Agreement:</strong>
  <%= @due.agreement_id %>
</p>

<p>
  <strong>Property:</strong>
  <%= @due.property_id %>
</p>

<p>
  <strong>Tenant:</strong>
  <%= @due.tenant_id %>
</p>

<p>
  <strong>Period from:</strong>
  <%= @due.period_from %>
</p>

<p>
  <strong>Period to:</strong>
  <%= @due.period_to %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @due.amount %>
</p>

<p>
  <strong>Paid amount:</strong>
  <%= @due.paid_amount %>
</p>

<p>
  <strong>Paid on:</strong>
  <%= @due.paid_on %>
</p>

<p>
  <strong>Payment date:</strong>
  <%= @due.payment_date %>
</p>

<%= link_to 'Edit', edit_due_path(@due) %> |
<%= link_to 'Back', dues_path %>